port = 'PORT'
proxy = 'IS_PROXIED'
num_workers = 'NUM_WORKERS'
log_level = 'LOG_LEVEL'
log_output = 'LOG_OUTPUT'
service_url = 'SERVICE_URL'
[proxy_store]
type = 'PROXY_STORAGE_TYPE'
max_image_width = 'PROXY_MAX_IMAGE_WIDTH'
max_image_height = 'PROXY_MAX_IMAGE_HEIGHT'
max_resize_image_width = 'PROXY_MAX_RESIZE_IMAGE_WIDTH'
max_resize_image_height = 'PROXY_MAX_RESIZE_IMAGE_HEIGHT'
