num_workers = 0
port = 8800
proxy = true
log_level = 'info'
# service_url = 'https://devimages.golos.today'
# max_image_size = 10000000 # 10mb
[proxy_store]
type = 'fs'
# max_image_width = 1024
# max_image_height = 1280
# max_resize_image_width = 2560
# max_resize_image_height = 1440
format = 'webp'
max_avatar_width = 200
max_avatar_height = 200
